### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by 3gf8jv4dv** [zkitefly/forge-maven-metadata#2]
The JSON provided by BMCLAPI includes the modified time of the build, but the timestamp of all builds in the JSON in this repo is `2333333333`.

<s>This results in HMCL where the time can be seen when selecting a Forge version when using BMCLAPI, but not when using the source from this repo.</s>

I am not sure it is technically possible to achieve similar results as BMCLAPI, but I am asking anyway.

**Comment by zkitefly** [comment]
其实，hmcl 并没有使用 modified 属性，所以我就输入了个无意义的固定值

而且，modified属性似乎并不是时间属性，bmclapi 中也没有关于时间的相关属性

hmcl 也没有显示相应版本的修改时间

**Comment by 3gf8jv4dv** [comment]
Oops. But the results confuse me.

<details>
<summary>BMCLAPI</summary>

![](https://github.com/user-attachments/assets/1166dbef-33a9-4d65-8747-b573a0ebb135)

</details>

<details>
<summary>zkitefly/forge-maven-metadata</summary>

![](https://github.com/user-attachments/assets/48ae8726-d593-431a-9522-84f7a87b21dd)

</details>

**Comment by zkitefly** [comment]
我想起来，是官方源（zkitefly/forge-maven-metadata）时，并不会读取 modified 属性， https://github.com/HMCL-dev/HMCL/pull/3251 仅仅是重新启用被遗弃的代码

而且 https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml 并没有提供关于 modified 相关参数，眼下的方法可能是读取 jar 中的数据，或者爬取网页数据

![image](https://github.com/user-attachments/assets/5636e06c-af41-40f0-91da-74b41b4fb66b)

**Comment by zkitefly** [comment]
我在思考这个东西要不要做 :thinking:

**Comment by 3gf8jv4dv** [comment]
> 我在思考这个东西要不要做 🤔

I think if it is too troublesome to implement, then forget it. If it is simple, give it a try.

**Comment by zkitefly** [comment]
> > 我在思考这个东西要不要做 🤔
> 
> I think if it is too troublesome to implement, then forget it. If it is simple, give it a try.

先等 HMCL 合并了该 PR，我再着手做这个东西

**Comment by zkitefly** [comment]
![image](https://github.com/user-attachments/assets/a96f11d4-8a1b-4cde-91ef-2395983e8e7f)

完成！

**Comment by zkitefly** [comment]
时间稍微和 BMCLAPI 的有不同，但日期应该相同
